site_name: Sleuth PR
docs_dir: docs/src
theme:
    name: readthedocs
    custom_dir: docs/theme/

nav:
    - Home: index.md
    - Triggers: triggers.md
    - Conditions: conditions.md
    - Variables: variables.md
    - Actions: actions.md
    - About: about.md


plugins:
    - macros:
        module_name: docs
