# Generated by Django 3.1.1 on 2020-09-23 23:34
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=512, verbose_name="email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=512,
                        verbose_name="username",
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=512,
                        null=True,
                        verbose_name="uid",
                    ),
                ),
                (
                    "installation",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="provider"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.CharField(db_index=True, max_length=512)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=255)),
                (
                    "on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created on",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_ids",
                        to="sleuthpr.installation",
                        verbose_name="installation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, default="", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=16384, verbose_name="description"
                    ),
                ),
                (
                    "on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created on",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="sleuthpr.repository",
                        verbose_name="repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pr_updated", "PR Updated"),
                            ("pr_created", "PR Created"),
                            ("cron", "Every 5 minutes"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="sleuthpr.rule",
                        verbose_name="installation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        db_index=True,
                        default="",
                        max_length=16384,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=16384, verbose_name="description"
                    ),
                ),
                (
                    "on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created on",
                    ),
                ),
                ("remote_id", models.CharField(db_index=True, max_length=512)),
                (
                    "source_branch_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=1024,
                        null=True,
                        verbose_name="source branch name",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=1024, verbose_name="url"),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="sleuthpr.repository",
                        verbose_name="repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=16384, verbose_name="description"
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        blank=True, max_length=16384, verbose_name="expression"
                    ),
                ),
                (
                    "on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created on",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="sleuthpr.rule",
                        verbose_name="rule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pr_merge", "PR Merge"),
                            ("pr_close", "PR Close"),
                            ("add_label", "Add Label"),
                        ],
                        db_index=True,
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=16384, verbose_name="description"
                    ),
                ),
                (
                    "on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created on",
                    ),
                ),
                ("parameters", models.JSONField()),
                ("order", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="sleuthpr.rule",
                        verbose_name="rule",
                    ),
                ),
            ],
        ),
    ]
