# Generated by Django 3.1.1 on 2020-09-28 21:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioncheckrun",
            name="pull_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="sleuthpr.pullrequest",
                verbose_name="pull_request",
            ),
        ),
    ]
