# Generated by Django 3.1.1 on 2020-09-24 21:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaluser",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=512, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="externaluser",
            name="name",
            field=models.CharField(
                db_index=True, max_length=512, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="externaluser",
            name="remote_id",
            field=models.CharField(
                db_index=True, max_length=512, null=True, verbose_name="uid"
            ),
        ),
        migrations.AlterField(
            model_name="externaluser",
            name="username",
            field=models.CharField(
                db_index=True, max_length=512, null=True, verbose_name="username"
            ),
        ),
    ]
