# Generated by Django 3.1.1 on 2020-09-30 19:26
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditioncheckrun",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure"), ("pending", "Pending"), ("error", "Error")],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PullRequestStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="value",
                    ),
                ),
                ("context", models.CharField(db_index=True, max_length=255, verbose_name="context")),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="sleuthpr.pullrequest",
                        verbose_name="pull_request",
                    ),
                ),
            ],
        ),
    ]
