# Generated by Django 3.1.1 on 2020-09-26 06:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0002_auto_20200924_2129"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="mergeable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="merged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="rebaseable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="source_sha",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=1024,
                null=True,
                verbose_name="source sha",
            ),
        ),
    ]
