# Generated by Django 3.1.1 on 2020-09-30 20:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0002_auto_20200930_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequestreviewer",
            name="state",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("dismissed", "Dismissed"),
                    ("changes_requested", "Changes requested"),
                    ("commented", "Commented"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="pullrequeststatus",
            name="state",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure"), ("pending", "Pending"), ("error", "Error")],
                db_index=True,
                max_length=20,
                verbose_name="state",
            ),
        ),
    ]
