# Generated by Django 3.1.1 on 2020-09-26 07:24
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0003_auto_20200926_0627"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequestCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.CharField(db_index=True, max_length=512)),
                (
                    "pull_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="sleuthpr.pullrequest",
                        verbose_name="pull_request",
                    ),
                ),
            ],
        ),
    ]
