# Generated by Django 3.1.1 on 2020-09-30 21:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0004_repositorybranch"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="base_sha",
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name="base sha"),
        ),
    ]
