# Generated by Django 3.1.1 on 2020-10-01 18:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0006_repositorycommit_repositorycommitparent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorycommit",
            name="message",
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name="message"),
        ),
    ]
