# Generated by Django 3.1.1 on 2020-10-01 20:12
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0007_auto_20201001_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorycommit",
            name="on",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="created on"),
        ),
        migrations.AddField(
            model_name="repositorycommit",
            name="pull_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commits",
                to="sleuthpr.pullrequest",
                verbose_name="pull_request",
            ),
        ),
    ]
