# Generated by Django 3.1.1 on 2020-10-07 20:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0009_auto_20201007_2015"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConditionCheckRun",
        ),
    ]
