# Generated by Django 3.1.1 on 2020-10-09 15:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0011_trigger_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="conflict",
            field=models.CharField(
                choices=[("true", "True"), ("false", "False"), ("unknown", "Unknown")],
                default="unknown",
                max_length=15,
            ),
        ),
    ]
