# Generated by Django 3.1.1 on 2020-10-09 16:07
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0012_pullrequest_conflict"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorycommit",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_commits",
                to="sleuthpr.externaluser",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="repositorycommit",
            name="committer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committers",
                to="sleuthpr.externaluser",
                verbose_name="committer",
            ),
        ),
    ]
