# Generated by Django 3.1.1 on 2020-10-09 23:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0013_auto_20201009_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="line_number",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="condition",
            name="line_number",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="rule",
            name="line_number",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="trigger",
            name="line_number",
            field=models.IntegerField(default=-1),
        ),
    ]
