# Generated by Django 3.1.1 on 2020-10-10 06:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleuthpr", "0015_actionresult"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repositorycommit",
            unique_together={("repository", "sha")},
        ),
    ]
