# Generated by Django 3.1.1 on 2020-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleuthpr', '0016_auto_20201010_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestreviewer',
            name='state',
            field=models.CharField(choices=[('approved', 'Approved'), ('dismissed', 'Dismissed'), ('changes_requested', 'Changes requested'), ('commented', 'Commented'), ('pending', 'Pending'), ('submitted', 'Submitted')], db_index=True, default='pending', max_length=20, verbose_name='state'),
        ),
    ]
