# Generated by Django 3.1.1 on 2020-09-16 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=255)),
                ('on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created on')),
            ],
        ),
    ]
