# Generated by Django 3.1.1 on 2020-09-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github.installation', verbose_name='installation')),
            ],
        ),
    ]
