name: Automations

on: [push, pull_request, pull_request_review, check_run]

jobs:
  run-sleuth-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://mrdonbrown/sleuth-pr-dev:0.0.17
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
