name: Upload Base Image

on:
  push:
    paths:
      - 'base.Dockerfile'

jobs:
  deploy-base-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_API_KEY: ${{ secrets.DOCKERHUB_API_KEY }}
        run: bin/release-base-dockerhub.sh